#pragma once

#define CFG_KEY_STRING static const constexpr char *

namespace config
{
    CFG_KEY_STRING WIFI_SSID = "NET_WIFI_SSID";
    CFG_KEY_STRING WIFI_PASSWD = "NET_WIFI_PASS";
    CFG_KEY_STRING USB_SWITCH = "HW_USB_TMP_SW";
    CFG_KEY_STRING UART_BAUD = "HW_UART_BAUD";
    CFG_KEY_STRING UART_STOP = "HW_UART_STOP";
    CFG_KEY_STRING UART_DATA = "HW_UART_DATA";
    CFG_KEY_STRING UART_PARITY = "HW_UART_PARITY";
}